Modify generate tests method
mozilla-services/pytest-axe pull request #43
Opened 2018-10-11 20:14 UTC by kimberlythegeek

Modified the way that tests are generated in order to enable the configuration of xfail within classes, as opposed to individual `conftest.py` files.

2018-10-11 22:32 UTC, davehunt approved these changes

2018-10-11 22:32 UTC, davehunt commented on pytest_axe/tests/test_axe.py
> +            defined in conftest.py.
It looks like the docstring needs updating here.

2018-10-12 15:40 UTC, m8ttyB requested changes
Looks great, just few items that were noted by Dave and I.

2018-10-12 15:40 UTC, m8ttyB commented on pytest_axe/parameterize_tests.py
> +    # xfail_rules = metafunc.config.xfail_rules
Did you intend to remove this or leave it as commented out?

2018-10-12 15:40 UTC, m8ttyB commented on pytest_axe/parameterize_tests.py
> +def parametrized_accessibility_rules(xfail_rules):
Woot \o/

2018-10-12 15:40 UTC, m8ttyB commented on pytest_axe/pytest_axe.py
> +    def __init__(self, selenium, context=None, options=None, impact=None):
Just a nit, how do you feel about adding a docstring here?

2018-10-12 18:09 UTC, merged